---
name: Pod-WikiDoc
version: 0.14
author:
  - David A Golden <dagolden@cpan.org>
abstract: Generate Pod from inline wiki style text
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Cwd: 0
  File::Basename: 0
  File::Find: 1
  File::Spec: 3
  File::Temp: 0.14
  File::pushd: 0.3
  Getopt::Lucid: 0.14
  IO::String: 1.06
  IPC::Run3: 0.033
  Parse::RecDescent: 1.94
  Pod::Usage: 1
  Probe::Perl: 0.01
  Scalar::Util: 1.02
  Test::More: 0.45
  Text::Balanced: 1.95
  perl: 5.006
provides:
  Parse::RecDescent::Pod::WikiDoc::Parser:
    file: lib/Pod/WikiDoc/Parser.pm
  Pod::WikiDoc:
    file: lib/Pod/WikiDoc.pm
    version: 0.14
  Pod::WikiDoc::Cookbook:
    file: lib/Pod/WikiDoc/Cookbook.pm
    version: 0.14
  Pod::WikiDoc::Parser:
    file: lib/Pod/WikiDoc/Parser.pm
generated_by: Module::Build version 0.28
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
no_index:
  file:
    - lib/Pod/WikiDoc/Cookbook.pm
