---
name: Pod-WikiDoc
version: 0.10
author:
  - David A Golden <dagolden@cpan.org>
abstract: ~
license: perl
requires:
  File::Find: 1
  File::Spec: 3
  File::Temp: 0.16
  File::pushd: 0.2
  Getopt::Long: 2.17
  IO::String: 1.06
  IPC::Run3: 0.020
  Parse::RecDescent: 1.94
  Pod::Usage: 1
  Scalar::Util: 1.02
  Test::More: 0.48
provides:
  Pod::WikiDoc:
    file: lib/Pod/WikiDoc.pm
    version: 0.10
  Pod::Wikidoc::Cookbook:
    file: lib/Pod/WikiDoc/Cookbook.pm
generated_by: Module::Build version 0.2702
