---
abstract: 'Generate Pod from inline wiki style text'
author:
  - 'David A Golden <dagolden@cpan.org>'
build_requires:
  Cwd: 0
  File::Basename: 0
  File::Find: 1
  File::Spec: 3
  File::Temp: 0
  IPC::Run3: 0.033
  Probe::Perl: 0.01
  Test::Builder: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300009, CPAN::Meta::Converter version 2.120351'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-WikiDoc
no_index:
  directory:
    - examples
  package:
    - DB
provides:
  Pod::WikiDoc:
    file: lib/Pod/WikiDoc.pm
    version: 0.19
requires:
  Carp: 0
  Getopt::Lucid: 0.14
  IO::String: 1.06
  Parse::RecDescent: 1.967006
  Pod::Usage: 1
  Scalar::Util: 1.02
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Pod-WikiDoc
  homepage: https://github.com/dagolden/pod-wikidoc
  repository: https://github.com/dagolden/pod-wikidoc.git
version: 0.19
